UPDATE hotel
SET
    short_desc = CASE id
                     WHEN 1 THEN 'A cozy hotel in New York with modern amenities and stunning city views.'
                     WHEN 2 THEN 'A luxurious hotel in New York with world-class service and elegant rooms.'
                     WHEN 3 THEN 'A budget-friendly hotel in New York with comfortable rooms and great service.'
                     WHEN 4 THEN 'A charming hotel in Zurich blending modern and traditional Swiss hospitality.'
                     WHEN 5 THEN 'A premium hotel in Zurich with luxurious rooms and exceptional service.'
                     WHEN 6 THEN 'An affordable hotel in Zurich with clean rooms and a convenient location.'
                     WHEN 7 THEN 'An elegant hotel in Paris with stylish rooms and breathtaking city views.'
                     WHEN 8 THEN 'A luxury hotel in Paris on the Champs-Élysées with premium services.'
                     WHEN 9 THEN 'An affordable yet charming hotel in Paris with cozy rooms and a perfect location.'
                     ELSE short_desc
        END,
    full_desc = CASE id
                    WHEN 1 THEN 'Nestled in the heart of New York, The Manhattan Haven offers a cozy retreat with modern amenities and breathtaking views of the city skyline. This hotel features elegantly designed rooms equipped with high-speed Wi-Fi, flat-screen TVs, and plush bedding, ensuring a comfortable stay for both leisure and business travelers. Guests can enjoy a complimentary breakfast each morning, served in a stylish dining area, along with access to a 24-hour fitness center and concierge services. Located just steps away from Times Square and Central Park, the hotel provides easy access to iconic landmarks, shopping, and dining. Recent guest reviews praise the attentive staff and the serene ambiance, making it an ideal choice for those seeking a blend of comfort and convenience in the bustling metropolis.'
                    WHEN 2 THEN 'Experience unparalleled luxury at the Empire Luxe Hotel, a haven in the vibrant heart of New York. This hotel boasts exquisitely designed rooms and suites, each adorned with marble bathrooms, premium linens, and state-of-the-art entertainment systems. Guests can indulge in gourmet dining at the on-site Michelin-starred restaurant, relax at the rooftop infinity pool with panoramic city views, or unwind in the luxurious spa offering a range of treatments. Situated near Wall Street and the Statue of Liberty, the hotel is perfect for those seeking a blend of business and leisure. Previous guests highlight the impeccable service, sophisticated decor, and prime location as standout features.'
                    WHEN 3 THEN 'The Big Apple Retreat is a budget-friendly hotel in New York, designed for travelers seeking comfort without compromising value. Featuring cozy rooms with essential amenities like free Wi-Fi, air conditioning, and a work desk, this hotel caters to both short-term visitors and extended stays. Guests can enjoy a continental breakfast and access to a shared lounge area. Located near the bustling Grand Central Terminal, it offers easy connectivity to public transport and proximity to major attractions like the Empire State Building. Reviews commend the friendly staff and clean accommodations, making it a popular choice for budget-conscious explorers.'
                    WHEN 4 THEN 'The Alpine Glow Hotel in Zurich combines modern elegance with traditional Swiss hospitality. This charming retreat features spacious rooms with wooden accents, panoramic views of the Alps, and amenities such as minibars and rainfall showers. Guests can savor authentic Swiss cuisine at the on-site restaurant or relax in the garden terrace. Perfectly located near Lake Zurich and the Old Town, the hotel is ideal for exploring cultural landmarks and scenic beauty. Visitors often praise the warm hospitality, tranquil setting, and attention to detail in every aspect of their stay.'
                    WHEN 5 THEN 'Zurich Grand Palace is a premium hotel that redefines hospitality in the heart of Zurich. Boasting opulent rooms with custom furnishings, private balconies, and cutting-edge technology, this hotel offers an unrivaled experience. Guests can enjoy a world-class spa, an indoor swimming pool, and a fine-dining restaurant featuring international and local cuisine. Its prime location near Bahnhofstrasse, the city’s premier shopping street, and the Zurich Opera House makes it a favorite among luxury travelers. Recent reviews highlight the exceptional service, exquisite design, and unforgettable dining experiences.'
                    WHEN 6 THEN 'Swiss Comfort Inn is an affordable hotel in Zurich, offering clean and comfortable accommodations for budget travelers. The hotel features simple yet functional rooms with free Wi-Fi, flat-screen TVs, and private bathrooms. Guests can start their day with a light breakfast and take advantage of the hotel’s central location near Zurich Main Station. Ideal for exploring the city’s museums, parks, and markets, this hotel is praised for its friendly staff and value for money, making it a practical choice for solo travelers and families alike.'
                    WHEN 7 THEN 'Hotel Paris Lumière is an elegant hotel situated in the romantic heart of Paris. With stylish rooms featuring contemporary decor, marble bathrooms, and views of the Eiffel Tower, this hotel offers a perfect blend of luxury and charm. Guests can enjoy a gourmet breakfast, access a fitness center, and explore the nearby Louvre and Notre-Dame. The hotel’s prime location in the 7th arrondissement is ideal for sightseeing and shopping. Guests rave about the attentive service, sophisticated ambiance, and the stunning rooftop terrace with city views.'
                    WHEN 8 THEN 'Hotel Paris Étoile is a luxury hotel located on the iconic Champs-Élysées in Paris. This hotel offers lavish rooms with silk draperies, private balconies, and panoramic views of the Arc de Triomphe. Guests can indulge in exquisite dining at the on-site restaurant, relax in the spa with a sauna and steam room, or explore the city’s fashion boutiques just steps away. Perfect for luxury seekers, the hotel’s central location and impeccable service have earned it high praise from international travelers for its grandeur and attention to detail.'
                    WHEN 9 THEN 'Hotel Paris Cozy is a charming hotel offering affordable luxury in the vibrant heart of Paris. Featuring an array of cozy rooms with modern touches—ranging from standard doubles to family suites—each is equipped with free high-speed Wi-Fi, flat-screen TVs, and stunning views of the city skyline or charming Parisian rooftops. Guests can indulge in a daily breakfast buffet featuring fresh croissants, local cheeses, and a selection of hot beverages, served in a bright dining area. The hotel’s prime location in a lively neighborhood near Montmartre and the iconic Sacré-Cœur Basilica provides easy access to cultural landmarks, with local cafes, artisan shops, and bustling markets just steps away. Celebrated by guests for its exceptionally friendly staff, immaculately clean rooms, and unbeatable value, this hotel is the perfect base for budget-conscious travelers eager to explore Paris.'
                    ELSE full_desc
        END
WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 9);